version = 1
SPDX-PackageName = "KDSoap"
SPDX-PackageSupplier = "<info@kdab.com>"
SPDX-PackageDownloadLocation = "https://www.github.com/KDAB/KDSoap"

#misc source code
[[annotations]]
path = ["unittests/**/**.xsd", "unittests/**/**.wsdl", "unittests/**/**.XSD", "unittests/**/**.xml", "unittests/**/**.qrc", "testtools/**.qrc", "examples/**/**.qrc", "examples/**/**.wsdl", "**.html", "**.css", "docs/manual/**.pdf", "**.bat", "**.pem"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

#artwork
[[annotations]]
path = ["images/**.png", "docs/api/**.png", "docs/**.png", "docs/**.odg", "examples/**/**.mng", "examples/**/**.gif"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

#misc documentation
[[annotations]]
path = ["**md", "**.txt", "**.html", "docs/manual/**.pdf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

#misc config files
[[annotations]]
path = ["CMakePresets.json", ".pre-commit-config.yaml", ".codespellrc", ".krazy", ".cmake-format.py", ".clang-format", ".clang-tidy", ".clazy", ".codedocs", ".gitignore", ".gitmodules", ".mdlrc", ".mdlrc.rb", ".pep8", ".pylintrc", "docs/api/Doxyfile.cmake", "distro/**", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "kdwsdl2cpp/schemas/soapenc-1.1.xsd"
precedence = "aggregate"
SPDX-FileCopyrightText = "2001 DevelopMentor and 2001 W3C (Massachusetts Institute of Technology, Institut National de Recherche en Informatique et en Automatique, Keio University). All Rights Reserved."
SPDX-License-Identifier = "W3C"

[[annotations]]
path = "kdwsdl2cpp/schemas/soapenc-1.2.xsd"
precedence = "aggregate"
SPDX-FileCopyrightText = "2003 W3C(R) (MIT, ERCIM, Keio), All Rights Reserved."
SPDX-License-Identifier = "W3C"

[[annotations]]
path = "kdwsdl2cpp/schemas/schemas.qrc"
precedence = "aggregate"
SPDX-FileCopyrightText = "2005 Tobias Koenig <tokoe@kde.org>"
SPDX-License-Identifier = "MIT"

#3rdparty
[[annotations]]
path = "cmake/ECM/modules/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The KDE Project"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["unittests/groupwise_wsdl/**.xsd", "unittests/groupwise_wsdl/**.wsdl"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2005-2006 Novell, Inc All Rights reserved."
SPDX-License-Identifier = "GPL-2.0-only OR LicenseRef-Novell"

[[annotations]]
path = "unittests/salesforce_wsdl/**.wsdl"
precedence = "aggregate"
SPDX-FileCopyrightText = "1999-2010 salesforce.com, inc. All Rights reserved."
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["unittests/soap_over_udp/**.wsdl", "unittests/soap_over_udp/docs.oasis-open.org/ws-dd/discovery/1.1/os/wsdd-discovery-1.1-schema-os.xsd", "unittests/soap_over_udp/www.w3.org/2006/03/addressing/ws-addr.xsd"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2009 OASIS(r) All Rights reserved."
SPDX-License-Identifier = "LicenseRef-OASIS"

[[annotations]]
path = "unittests/webcalls_wsdl/**.wsdl"
precedence = "aggregate"
SPDX-FileCopyrightText = "2003-2004 The Sporting Exchange Limited. All rights reserved."
SPDX-License-Identifier = "LicenseRef-SportingExchange"

[[annotations]]
path = ["unittests/ws_discovery_wsdl/schemas.xmlsoap.org/ws/2005/04/discovery/ws-discovery.xsd", "unittests/ws_discovery_wsdl/schemas.xmlsoap.org/ws/2004/08/addressing", "unittests/ws_discovery_wsdl/**.wsdl"]
precedence = "aggregate"
SPDX-FileCopyrightText = "pyright © 2002-2004 BEA Systems Inc., International Business Machines Corporation, Microsoft Corporation, Inc, SAP AG, and Sun Microsystems, Inc.. All rights reserved."
SPDX-License-Identifier = "LicenseRef-Microsoft"

# doxygen awesome
[[annotations]]
path = "docs/api/doxygen-awesome.css"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 - 2023 jothepro"
SPDX-License-Identifier = "MIT"
