# SPDX-FileCopyrightText: 2023 Klarälvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>
#
# SPDX-License-Identifier: MIT

name: Tidy and Clazy

on:
  push:
    branches:
      - master
      - kdsoap-2.1
      - kdsoap-2.2
  pull_request:
    branches:
      - master
      - kdsoap-2.1
      - kdsoap-2.2

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

        config:
          - name: clang-tidy
            preset: "clang-tidy"
            qt_version: "6.6"

          - name: clazy
            preset: "clazy"
            qt_version: "6.6"
            apt_pgks:
              - clazy

    steps:
      - name: Install Qt ${{ matrix.config.qt_version }} with options and default aqtversion
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.config.qt_version }}
          cache: true

      - name: Install ninja-build tool (must be after Qt due PATH changes)
        uses: turtlesec-no/get-ninja@main

      - name: Install dependencies on Ubuntu (${{ join(matrix.config.apt_pgks, ' ') }})
        if: ${{ runner.os == 'Linux' && matrix.config.apt_pgks }}
        run: |
          sudo apt update -qq
          echo ${{ join(matrix.config.apt_pgks, ' ') }} | xargs sudo apt install -y

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Fetch Git submodules
        run: git submodule update --init --recursive

      - name: Configure project
        run: >
          cmake --preset=${{ matrix.config.preset }}

      - name: Build Project
        run: cmake --build --preset=${{ matrix.config.preset }}
